apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Dell\Downloads\kompose\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Dell\Downloads\kompose\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: neo4j
    spec:
      containers:
        - args:
            - neo4j
            - start
          env:
            - name: NEO4J_AUTH
              value: neo4j/admin1234
          image: neo4j:4.4
          name: neo4j
          ports:
            - containerPort: 7474
              protocol: TCP
            - containerPort: 7687
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: neo4j-data
            - mountPath: /docker-entrypoint-initdb.d
              name: neo4j-cm1
      restartPolicy: Always
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data
        - configMap:
            name: neo4j-cm1
          name: neo4j-cm1
