apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: neo4j-data
  name: neo4j-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi