apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: "C:\\Users\\Dell\\Downloads\\kompose\\kompose.exe convert -f docker-compose.yaml"
    kompose.version: "1.34.0 (cbf2835db)"
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  template:
    metadata:
      annotations:
        kompose.cmd: "C:\\Users\\Dell\\Downloads\\kompose\\kompose.exe convert -f docker-compose.yaml"
        kompose.version: "1.34.0 (cbf2835db)"
      labels:
        io.kompose.service: server
    spec:
      containers:
        - name: server
          image: cloudala/server
          ports:
            - containerPort: 4000
              protocol: TCP
          envFrom:
            - secretRef:
                name: server-secret
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 10
      restartPolicy: Always