services:
  server:
    image: cloudala/server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=admin1234
    depends_on:
      - neo4j

  client:
    image: cloudala/client
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://server:4000/api
    depends_on:
      - server

  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/admin1234
    volumes:
      - neo4j_data:/data
      - ./neo4j/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: ["neo4j", "start"]

volumes:
  neo4j_data: